global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Trading system metrics
  - job_name: 'algotrading-system'
    static_configs:
      - targets: ['algotrading-agent:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # Trading API health checks
  - job_name: 'trading-api-health'
    static_configs:
      - targets: ['algotrading-agent:8080']
    metrics_path: '/health'
    scrape_interval: 30s