groups:
  - name: trading_system_alerts
    rules:
      # Trading Performance Alerts
      - alert: HighDailyLoss
        expr: trading_daily_pnl_pct < -2.0
        for: 1m
        labels:
          severity: critical
          category: trading
        annotations:
          summary: "Daily loss limit exceeded"
          description: "Daily P&L is {{ $value }}%, exceeding the -2% limit"
          
      - alert: MaxDrawdownExceeded
        expr: risk_current_drawdown_percent >= 5.0
        for: 30s
        labels:
          severity: critical
          category: risk
        annotations:
          summary: "Maximum drawdown exceeded"
          description: "Current drawdown is {{ $value }}%, exceeding the 5% limit"
          
      - alert: ConsecutiveLosses
        expr: trading_consecutive_losses >= 5
        for: 0s
        labels:
          severity: warning
          category: trading
        annotations:
          summary: "High consecutive losses detected"
          description: "{{ $value }} consecutive losing trades detected"
          
      # System Health Alerts
      - alert: HighMemoryUsage
        expr: system_memory_usage_mb > 800
        for: 2m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "High memory usage detected"
          description: "System memory usage is {{ $value }}MB (>800MB)"
          
      - alert: ComponentFailure
        expr: trading_system_up == 0
        for: 30s
        labels:
          severity: critical
          category: system
        annotations:
          summary: "Trading system component failure"
          description: "One or more system components are not running"
          
      - alert: HighAPIErrorRate
        expr: rate(system_api_errors_total[5m]) > 0.1
        for: 1m
        labels:
          severity: warning
          category: system
        annotations:
          summary: "High API error rate"
          description: "API error rate is {{ $value | humanizePercentage }} over 5 minutes"
          
      # Risk Management Alerts
      - alert: PositionConcentrationRisk
        expr: portfolio_max_position_percent > 10.0
        for: 1m
        labels:
          severity: warning
          category: risk
        annotations:
          summary: "Position concentration risk"
          description: "Single position represents {{ $value }}% of portfolio (>10%)"
          
      - alert: LowCashBalance
        expr: portfolio_cash_percent < 10.0
        for: 5m
        labels:
          severity: info
          category: trading
        annotations:
          summary: "Low cash balance"
          description: "Cash balance is {{ $value }}% of portfolio (<10%)"
          
      # Performance Alerts
      - alert: LowWinRate
        expr: trading_win_rate_percent < 40.0 and trading_total_trades > 20
        for: 10m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Low win rate detected"
          description: "Win rate is {{ $value }}% with {{ $labels.total_trades }} trades"
          
      - alert: PoorProfitFactor
        expr: trading_profit_factor < 1.2 and trading_total_trades > 10
        for: 5m
        labels:
          severity: info
          category: performance
        annotations:
          summary: "Poor profit factor"
          description: "Profit factor is {{ $value }} (<1.2 target)"