# Algotrading Agent Configuration

# Global settings
app:
  name: "Algotrading Agent"
  version: "1.0.0"
  log_level: "INFO"
  data_dir: "/app/data"
  
# News Scraper Configuration
news_scraper:
  update_interval: 10  # 10 seconds for news-driven trading speed
  sources:
    - name: "Reuters Business"
      type: "rss"
      url: "https://feeds.reuters.com/reuters/businessNews"
    - name: "Yahoo Finance"
      type: "rss" 
      url: "https://feeds.finance.yahoo.com/rss/2.0/headline"
    - name: "MarketWatch"
      type: "rss"
      url: "http://feeds.marketwatch.com/marketwatch/marketpulse/"
    - name: "Seeking Alpha"
      type: "rss"
      url: "https://seekingalpha.com/market_currents.xml"
    - name: "Bloomberg Markets"
      type: "rss"
      url: "https://feeds.bloomberg.com/markets/news.rss"
    - name: "CNBC Markets"
      type: "rss"
      url: "https://www.cnbc.com/id/15839135/device/rss/rss.html"

# News Filter Configuration  
news_filter:
  min_score: 0.3
  recency_weight: 0.5
  keywords:
    - pattern: "earnings|revenue|profit"
      weight: 1.5
    - pattern: "merger|acquisition|buyout"
      weight: 2.0
    - pattern: "fda|approval"
      weight: 1.8
    - pattern: "partnership|deal"
      weight: 1.2
    # Breaking news patterns for immediate trading
    - pattern: "beats? (estimates?|expectations?)|smashes? (estimates?|expectations?)"
      weight: 3.0
      priority: "breaking"
    - pattern: "misses? (estimates?|expectations?)|disappoints?"
      weight: 3.0  
      priority: "breaking"
    - pattern: "halted|suspended|resumed"
      weight: 2.5
      priority: "breaking"
    - pattern: "breakthrough|major deal|blockbuster"
      weight: 2.5
      priority: "breaking"
  blacklist:
    - "celebrity"
    - "sports"
    - "entertainment"
  source_weights:
    "Reuters Business": 0.9
    "Yahoo Finance": 0.7
    "MarketWatch": 0.8

# News Analysis Brain Configuration
news_analysis_brain:
  sentiment_threshold: 0.1
  entity_patterns:
    companies:
      - "Apple Inc"
      - "Microsoft Corp"
      - "Tesla Inc"
    sectors:
      - "technology"
      - "healthcare" 
      - "finance"
  impact_keywords:
    "breakthrough": 0.3
    "record": 0.25
    "massive": 0.2
    "significant": 0.15

# AI Analyzer Configuration
ai_analyzer:
  enabled: true                     # Set to true to enable AI analysis
  
  # Primary AI Provider Selection (choose one)
  provider: "openai"                # Current active provider
  
  # Provider-specific configurations
  providers:
    openai:
      enabled: true
      model: "gpt-3.5-turbo"       # Options: gpt-3.5-turbo, gpt-4, gpt-4-turbo
      api_key_env: "OPENAI_API_KEY"
      base_url: "https://api.openai.com/v1/chat/completions"
      timeout: 30
      max_tokens: 800
      temperature: 0.3
      
    groq:
      enabled: true  
      model: "llama3-8b-8192"      # Options: llama3-8b-8192, llama3-70b-8192, mixtral-8x7b-32768
      api_key_env: "GROQ_API_KEY"
      base_url: "https://api.groq.com/openai/v1/chat/completions"
      timeout: 30
      max_tokens: 800
      temperature: 0.3
      
    anthropic:
      enabled: true
      model: "claude-3-sonnet-20240229"  # Options: claude-3-sonnet-20240229, claude-3-haiku-20240307
      api_key_env: "ANTHROPIC_API_KEY"
      base_url: "https://api.anthropic.com/v1/messages"
      timeout: 30
      max_tokens: 800
      
    local:
      enabled: false
      model: "llama3"              # Local model name (for Ollama, etc.)
      base_url: "http://localhost:11434/api/generate"
      timeout: 60
      
  # Fallback chain - if primary provider fails, try these in order
  fallback_chain: ["groq", "openai", "anthropic", "traditional"]
  
  # General settings
  max_retries: 3                   # Maximum retry attempts per provider
  batch_size: 5                    # Number of news items to analyze in parallel
  fallback_enabled: true           # Use traditional analysis if all AI providers fail
  
  # AI Analysis Weighting (how much to trust AI vs traditional analysis)
  # NOTE: These weights should sum to 1.0 for proper blending
  ai_weight: 0.7                   # AI analysis weight (0.0 to 1.0) - Default: trust AI more
  traditional_weight: 0.3          # Traditional analysis weight (0.0 to 1.0) - Fallback validation

# News Impact Scorer Configuration
news_impact_scorer:
  enable_scoring: true
  min_impact_threshold: 0.6    # Only process news with impact score >= 0.6
  learning_enabled: true       # Enable learning from trade outcomes
  hype_detection: true         # Enable viral/social media hype detection
  
  # Enhanced Temporal Dynamics Parameters
  enhanced_temporal_analysis: true    # Enable temporal dynamics analysis
  hype_duration_tracking: true        # Track how long sentiment momentum lasts
  peak_detection_windows: true        # Analyze peak impact timing windows
  decay_pattern_analysis: true        # Analyze how fast hype influence fades
  
  # Enhanced Strength Correlation Parameters  
  strength_correlation_analysis: true # Enable sentiment-to-price velocity mapping
  volume_correlation_tracking: true   # Track hype-to-volume correlations
  volatility_pattern_prediction: true # Predict volatility based on sentiment strength
  
  # Enhanced Market Context Parameters
  sector_momentum_analysis: true      # Analyze sector-specific hype responses
  market_regime_detection: true       # Detect bull/bear market impact on hype
  time_of_day_analysis: true          # Analyze time-of-day impact effectiveness
  
  # Tuning Parameters for Enhanced Analysis
  temporal_weight: 0.3                # Weight for temporal dynamics in scoring (0.0-1.0)
  strength_weight: 0.25               # Weight for strength correlation in scoring (0.0-1.0)
  market_context_weight: 0.2          # Weight for market context in scoring (0.0-1.0)
  traditional_weight: 0.25            # Weight for traditional impact scoring (0.0-1.0)
  
  # Performance Optimization
  cache_enhanced_calculations: true   # Cache expensive calculations
  batch_enhanced_analysis: true       # Process enhanced analysis in batches
  max_enhanced_items_per_batch: 50    # Maximum items per enhanced analysis batch

# Decision Engine Configuration
decision_engine:
  min_confidence: 0.05            # Lowered to 0.05 to generate more trades
  max_position_size: 1000
  sentiment_weight: 0.4
  impact_weight: 0.4              # Increased impact weight
  recency_weight: 0.2             # Decreased recency weight
  default_stop_loss_pct: 0.05     # 5% stop loss
  default_take_profit_pct: 0.10   # 10% take profit
  
  # Enhanced Analysis Integration
  enable_enhanced_analysis: true   # Enable enhanced NewsImpactScorer integration
  temporal_weight: 0.2             # Weight for temporal dynamics in decision making
  strength_correlation_weight: 0.15 # Weight for strength correlation analysis
  market_context_weight: 0.15     # Weight for market context analysis
  
  # Enhanced Target Adjustment Parameters
  enable_dynamic_targeting: true   # Enable enhanced target adjustment based on volatility/momentum
  max_take_profit_boost: 1.5       # Maximum take-profit multiplier (1.5 = 50% boost)
  max_stop_loss_tightening: 0.8    # Minimum stop-loss multiplier (0.8 = 20% tighter)
  volatility_adjustment_factor: 1.3 # Maximum volatility-based adjustment factor
  
  # Momentum and Breaking News Sensitivity
  breaking_news_multiplier: 1.5    # Multiplier for breaking news momentum
  strong_signal_threshold: 0.7     # Threshold for considering signal "strong"
  high_confidence_source_count: 3  # Number of sources needed for "high confidence"

# Risk Manager Configuration
risk_manager:
  max_portfolio_value: 100000     # $100k virtual money
  max_position_pct: 0.05          # 5% per position
  max_daily_loss_pct: 0.02        # 2% daily loss limit
  max_sector_exposure_pct: 0.20   # 20% per sector
  correlation_threshold: 0.7
  blacklisted_symbols:
    - "PENN"  # Example blacklisted symbol

# Statistical Advisor Configuration
statistical_advisor:
  min_trades_for_analysis: 10
  lookback_days: 30
  confidence_threshold: 0.6

# Trade Manager Configuration
trade_manager:
  polling_interval: 60              # 1 minute polling frequency
  max_active_trades: 10             # Maximum concurrent trades in queue
  price_flexibility_pct: 0.01       # 1% price flexibility for market orders
  trade_timeout_hours: 24           # Cancel trades after 24 hours
  max_retries: 3                    # Maximum retry attempts for failed orders
  enable_dynamic_adjustments: true  # Enable stop-loss/take-profit adjustments

# Trailing Stop Manager Configuration
trailing_stop_manager:
  enable_trailing_stops: true       # Enable automatic trailing stop-loss functionality
  
  # Default Trailing Settings
  default_trailing_percent: 3.0     # 3% trailing stop (percentage-based)
  default_trailing_amount: 0.50     # $0.50 trailing stop (dollar-based alternative)
  min_profit_threshold: 0.02        # 2% minimum profit before trailing begins
  
  # Noise Filtering (Prevent premature exits on small moves)
  noise_filter_enabled: true        # Enable noise filtering
  min_move_threshold: 0.01          # 1 cent minimum price move to consider
  consolidation_period_minutes: 5   # 5 minute consolidation period
  
  # Safety Limits
  max_daily_updates_per_symbol: 10  # Maximum trailing adjustments per symbol per day
  update_interval: 60               # Check positions every 60 seconds
  max_concurrent_updates: 5         # Limit concurrent API calls
  
  # Risk Management
  max_trail_distance_percent: 10.0  # Maximum distance to trail (10% of current price)
  min_trail_distance_percent: 0.5   # Minimum distance to trail (0.5% of current price)
  enable_weekend_updates: false     # Disable updates during weekends
  
  # Performance Settings
  cache_position_data: true         # Cache position data for performance
  batch_processing: true            # Process multiple symbols together
  emergency_stop_enabled: true      # Emergency stop if too many failures

# Observability & Metrics Configuration
observability:
  # Metrics Collection
  metrics_collector:
    collection_interval: 30          # Collect metrics every 30 seconds
    history_retention_hours: 168     # Keep 1 week of history
    enable_prometheus_export: true   # Enable Prometheus metrics endpoint
    prometheus_port: 9090            # Port for Prometheus scraping
    
  # Dashboard & API
  dashboard:
    enable_modern_dashboard: true    # Enable new observability dashboard
    auto_refresh_seconds: 30         # Dashboard auto-refresh interval
    show_enhanced_features: true     # Show trailing stops, AI metrics, etc.
    
  # Performance Monitoring
  performance:
    track_api_response_times: true   # Monitor API call performance
    track_memory_usage: true         # Monitor system memory usage
    alert_on_high_error_rate: true   # Alert if error rate > 5%
    alert_on_drawdown: true          # Alert if drawdown > 10%
    
  # Alerting System
  alerts:
    enabled: true                    # Enable alert system
    evaluation_interval: 60          # Evaluate rules every 60 seconds
    
    # Alert Channels
    channels:
      log:
        enabled: true
        level: "WARNING"             # Minimum log level for alerts
      console: 
        enabled: true
        show_in_dashboard: true      # Show alerts in dashboard
      email:
        enabled: false
        smtp_host: "smtp.gmail.com"
        smtp_port: 587
        username: ""
        password: ""
        from_address: "alerts@algotrading.com"
        to_addresses: []
      webhook:
        enabled: false
        url: ""
        timeout: 10
      slack:
        enabled: false
        webhook_url: ""
        channel: "#trading-alerts"
    
    # Alert Thresholds
    thresholds:
      max_daily_loss_pct: -2.0           # Alert if daily loss > 2%
      max_drawdown_pct: 5.0               # Alert if drawdown > 5%
      max_consecutive_losses: 5           # Alert after 5 consecutive losses
      high_memory_usage_mb: 800           # Alert if memory > 800MB
      max_api_error_rate: 0.10            # Alert if error rate > 10%
      min_cash_balance_pct: 10.0          # Alert if cash < 10%
      max_position_concentration_pct: 10.0 # Alert if single position > 10%
    
  # Log Aggregation & Analysis
  log_aggregator:
    enabled: true                    # Enable structured log aggregation
    db_path: "/app/data/logs.db"     # SQLite database for log storage
    max_memory_logs: 1000            # Maximum logs kept in memory
    retention_days: 30               # Days to retain logs in database
    auto_cleanup: true               # Automatically clean old logs
    
    # Log Classification
    enable_auto_classification: true  # Automatically classify log entries
    enable_metadata_extraction: true # Extract structured metadata from logs
    
  # Trading Analytics  
  trading_analytics:
    calculate_sharpe_ratio: true     # Calculate risk-adjusted returns
    calculate_profit_factor: true    # Calculate gross profit/loss ratio
    track_win_rate: true             # Track percentage of winning trades
    track_avg_trade_duration: true   # Track average time in positions
    
  # Correlation Analysis
  correlation_tracker:
    data_dir: "/app/data"            # Directory to store correlation data
    max_results: 1000                # Maximum correlation results to keep
    historical_test_enabled: true    # Enable historical correlation testing
    auto_track_trades: true          # Automatically track live trade correlations
    
  # Trade Performance Tracking
  trade_performance_tracker:
    data_dir: "/app/data"            # Directory to store trade outcome data
    max_trades: 1000                 # Maximum trade records to keep
    enable_detailed_analysis: true   # Enable detailed success/failure analysis
    track_news_attribution: true     # Track which news led to which outcomes
    
  # Decision Analysis
  decision_analyzer:
    data_dir: "/app/data"            # Directory to store decision analysis data
    short_analysis_window: 24        # Hours for short-term analysis
    medium_analysis_window: 168      # Hours for medium-term analysis (1 week)
    long_analysis_window: 720        # Hours for long-term analysis (1 month)
    enable_pattern_detection: true   # Enable decision pattern detection
    
  # Trading Dashboard
  trading_dashboard:
    refresh_interval: 30             # Dashboard refresh interval in seconds
    max_recent_trades: 20            # Maximum recent trades to display
    max_insights: 10                 # Maximum insights/recommendations to show
    enable_html_export: true         # Enable HTML dashboard export

# Alpaca API Configuration
alpaca:
  paper_trading: true
  base_url: "https://paper-api.alpaca.markets"
  data_url: "https://data.alpaca.markets"
  # API keys should be set via environment variables:
  # ALPACA_API_KEY and ALPACA_SECRET_KEY

# Trading Costs Configuration
trading_costs:
  # Paper trading vs live trading
  paper_trading_costs: false        # Apply costs in paper trading (for realistic backtesting)
  
  # Commission structures (choose one)
  commission_model: "zero"          # Options: "zero", "per_share", "per_trade", "percentage"
  
  # Per-trade flat commission (e.g., $1.00 per trade)
  per_trade_commission: 0.00        # USD per trade (buy or sell)
  
  # Per-share commission (e.g., $0.005 per share)  
  per_share_commission: 0.00        # USD per share
  per_share_minimum: 0.00           # Minimum commission per trade
  per_share_maximum: 0.00           # Maximum commission per trade (0 = no cap)
  
  # Percentage-based commission (e.g., 0.1% = 0.001)
  percentage_commission: 0.00       # Percentage of trade value (0.001 = 0.1%)
  percentage_minimum: 0.00          # Minimum commission per trade
  percentage_maximum: 0.00          # Maximum commission per trade (0 = no cap)
  
  # Additional fees
  regulatory_fees:
    # SEC fees (US stocks) - typically 0.0000278 (2.78 per $100k)
    sec_fee_rate: 0.0000278         # Percentage of sale proceeds (sells only)
    
    # FINRA Trading Activity Fee (TAF) - typically 0.000166 (16.6 per $100k)  
    taf_fee_rate: 0.000166          # Percentage of sale proceeds (sells only)
    
    # Other regulatory fees
    other_regulatory_fees: 0.00     # Fixed amount per trade
    
  # Market data fees (if applicable)
  market_data_fees:
    enabled: false                  # Apply market data subscription costs
    monthly_cost: 0.00              # Monthly market data subscription
    real_time_quotes: 0.00          # Cost per month for real-time quotes
    
  # Currency conversion fees (for international stocks)
  fx_fees:
    enabled: false                  # Apply FX conversion fees
    fx_spread_bps: 0                # Basis points spread on FX conversion (100 bps = 1%)
    fx_minimum: 0.00                # Minimum FX conversion fee
    
  # Borrowing costs (for short selling)
  borrowing_costs:
    enabled: false                  # Apply borrowing costs for short positions
    daily_rate: 0.00                # Daily borrowing rate (percentage)
    minimum_daily_fee: 0.00         # Minimum daily borrowing fee
    
  # Common broker presets (uncomment to use)
  broker_presets:
    # Alpaca (current) - Commission-free stocks
    alpaca:
      per_trade_commission: 0.00
      sec_fee_rate: 0.0000278
      taf_fee_rate: 0.000166
      
    # Interactive Brokers - Tiered pricing
    interactive_brokers:
      commission_model: "per_share"
      per_share_commission: 0.005   # $0.005 per share
      per_share_minimum: 1.00       # $1.00 minimum
      per_share_maximum: 1.00       # 1% of trade value maximum
      sec_fee_rate: 0.0000278
      taf_fee_rate: 0.000166
      
    # Charles Schwab - Commission-free stocks  
    schwab:
      per_trade_commission: 0.00
      sec_fee_rate: 0.0000278
      taf_fee_rate: 0.000166
      
    # E*TRADE - Commission-free stocks
    etrade:
      per_trade_commission: 0.00
      sec_fee_rate: 0.0000278
      taf_fee_rate: 0.000166
      
    # TD Ameritrade - Commission-free stocks
    td_ameritrade:
      per_trade_commission: 0.00
      sec_fee_rate: 0.0000278
      taf_fee_rate: 0.000166
      
    # Robinhood - Commission-free (but has PFOF)
    robinhood:
      per_trade_commission: 0.00
      # Note: Payment for order flow may result in worse execution prices
      
    # Traditional broker example
    traditional_broker:
      commission_model: "per_trade"
      per_trade_commission: 9.95    # $9.95 per trade
      sec_fee_rate: 0.0000278
      taf_fee_rate: 0.000166
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/app/logs/algotrading.log"
  max_size: "10MB"
  backup_count: 5